### ISSUE TITLE
unknown lock type 'MonitorLock'"

### ISSUE THREAD

**Issue by nazakli** [espertechinc/nesper#8]
Hi, 

I am using nuget package of nesper. As you can see following error output, it couldn't find monitor lock type and couldn't start default service provider 

```
        static EPRuntime _runtime;
        static List<string> eplStatements;
        static MessageHandler mh;
        static Configuration nesperConf;
        static EPServiceProvider epService;

        private static void InitializeNesper()
        {
            nesperConf = new Configuration();
            nesperConf.AddEventType(typeof(Payload));
            if (nesperConf.EngineDefaults.ThreadingConfig.IsInternalTimerEnabled)
            {
                Console.WriteLine("enabled");
            };
            epService = EPServiceProviderManager.GetDefaultProvider(nesperConf);
            _runtime = epService.EPRuntime;
            mh = new MessageHandler();
            mh.UpdatePrediction += Predict;
        }

```

The type initializer for 'com.espertech.esper.compat.threading.LockManager' threw an exception.

`
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'com.espertech.esper.client.EPServiceProviderManager' threw an exception.
  Source=NEsper
  TypeName=com.espertech.esper.client.EPServiceProviderManager
  StackTrace:
       at com.espertech.esper.client.EPServiceProviderManager.GetDefaultProvider(Configuration configuration)
       at MT4EventMontior.Program.InitializeNesper() in c:\EventMontior\Program.cs:line 46
       at MT4EventMontior.Program.Main(String[] args) in c:\EventMontior\Program.cs:line 89
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'com.espertech.esper.compat.threading.LockManager' threw an exception.
       Source=NEsper
       TypeName=com.espertech.esper.compat.threading.LockManager
       StackTrace:
            at com.espertech.esper.compat.threading.LockManager.CreateLock(Type typeCategory)
            at com.espertech.esper.client.EPServiceProviderManager..cctor()
       InnerException: 
            HResult=-2147024809
            **Message=unknown lock type 'MonitorLock'**
            Source=NEsper
            StackTrace:
                 at com.espertech.esper.compat.threading.LockManager..cctor()
            InnerException: 
`

**Comment by agtokty** [comment]
Hi, I was getting this error too. Than I realize that my default application enviroment is was not set to "en-US". 


I think the problem is happening [here](https://github.com/espertechinc/nesper/blob/master/NEsper/NEsper/compat/threading/LockManager.cs#L48)

"MonitoLock" is translated to "MONİTORLOCK" in my case.(my culture was "tr-TR")


  After adding these line to my application startup section, the problem is solved.

```
Threading.Thread.CurrentThread.CurrentCulture = new Globalization.CultureInfo("en-US");
CultureInfo.DefaultThreadCurrentCulture = new Globalization.CultureInfo("en-US");
```

**Comment by ajaxx** [comment]
Yeah, but you shouldn't have to convert culture for that to work properly.  I'm going to see how much effort would be required to move this to the EngineDefaults portion of the esper configuration.  Thanks for the info, the culture bit helps a lot.

**Comment by ajaxx** [comment]
As of 6.1.0 locks are created by an ILockManager instance that must be assigned as part of the container.  Previously much of the magic was handled by a static class and this made it difficult to diagnose why things went wrong.  Henceforth, choices like locking mechanism are considerably more explicit.
